# References:
# https://docs.travis-ci.com/user/job-lifecycle/
# https://docs.travis-ci.com/user/languages/cpp/
# https://docs.travis-ci.com/user/installing-dependencies
# https://docs.travis-ci.com/user/customizing-the-build/

os: linux
dist: bionic
language: cpp
compiler: gcc

before_install:
  - sudo apt-get update
  #- sudo apt-get -y build-dep freewheeling
  #- sudo apt-get -y install liblo-dev

script:
  #- autoreconf -if
  #- ./configure
  - cd src
  - make
  - ./main
