version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - compile
      - run

jobs:
  compile:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: cd src && make

  run:
    - run: cd src && ./main
