version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - compile
      - link:
          requires: 
            - compile


jobs:

  compile:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: cd src && make

  link:
    docker:
      - image: gcc:8.2
    steps:
      # instead of checking out, restore workspace (will merge all parallel containers from previous job)
      - attach_workspace:
          at: output
      - run: ls -la output
      - run: mv output/* .
      # link the compiled files into an executable
      - run: gcc -o program *.o
      # confirm program exists and is executable
      - run: ls -la
      - run: ./program
      # persist as artifact
      - store_artifacts:
          path: program
