name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        cd src
        make all
        ls -la

    - name: Run
      run: |
        cd src
        make test

    - name: Clean
      run: |
        cd src
        make clean
